### PR TITLE
feature:raw data export

### PR DESCRIPTION
**Pull request by kruzhambus**

### CODE REVIEW

**Comment by yevgenypats** [comment]
Hey team 👋 ! Im Yevgeny, maintainer and founder @ [CloudQuery](https://github.com/cloudquery/cloudquery), an open source high performance ELT framework.

We would love to help with an initial version of CloudQuery [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), if you can help us maintain it. It should solve this issue and enable your users to sync Swetric data to any database/datalake of the growing number of [CQ destinations](https://www.cloudquery.io/docs/plugins/destinations/overview).

See similar thing we did with [Plausible API](https://www.cloudquery.io/docs/plugins/sources/plausible/overview), [Plausible Docs](https://plausible.io/docs/integration-guides#bigquery) and [discussion](https://github.com/plausible/analytics/discussions/1777)

**Comment by kruzhambus** [comment]
> 

Thanks for the information, I wrote to the founder, he will respond later

**Comment by Blaumaus** [comment]
> Hey team 👋 ! Im Yevgeny, maintainer and founder @ [CloudQuery](https://github.com/cloudquery/cloudquery), an open source high performance ELT framework.
> 
> We would love to help with an initial version of CloudQuery [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), if you can help us maintain it. It should solve this issue and enable your users to sync Swetric data to any database/datalake of the growing number of [CQ destinations](https://www.cloudquery.io/docs/plugins/destinations/overview).
> 
> See similar thing we did with [Plausible API](https://www.cloudquery.io/docs/plugins/sources/plausible/overview), [Plausible Docs](https://plausible.io/docs/integration-guides#bigquery) and [discussion](https://github.com/plausible/analytics/discussions/1777)

Hi @yevgenypats, yes that would be amazing. Sure, we will help you guys to maintain Swetrix plugin for CloudQuery!

**Comment by yevgenypats** [comment]
> > Hey team 👋 ! Im Yevgeny, maintainer and founder @ [CloudQuery](https://github.com/cloudquery/cloudquery), an open source high performance ELT framework.
> > We would love to help with an initial version of CloudQuery [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), if you can help us maintain it. It should solve this issue and enable your users to sync Swetric data to any database/datalake of the growing number of [CQ destinations](https://www.cloudquery.io/docs/plugins/destinations/overview).
> > See similar thing we did with [Plausible API](https://www.cloudquery.io/docs/plugins/sources/plausible/overview), [Plausible Docs](https://plausible.io/docs/integration-guides#bigquery) and [discussion](https://github.com/plausible/analytics/discussions/1777)
> 
> Hi @yevgenypats, yes that would be amazing. Sure, we will help you guys to maintain Swetrix plugin for CloudQuery!

Awesome! We will start working on that soon and update here once we have a first version! One thing if you can do please, when you have time is open a new empty repo called `https://github.com/Swetrix/cq-source-swetrix` so we can fork and open a PR with the first version.

**Comment by Blaumaus** [comment]
@yevgenypats thank you. Done: https://github.com/Swetrix/cq-source-swetrix

**Comment by yevgenypats** [comment]
Hey @Blaumaus , we are starting to kick the tires on that. Do you have an API documentation in any chance (bot for self-hosted and managed), I wasn't able to quickly find it?

**Comment by Blaumaus** [comment]
> Hey @Blaumaus , we are starting to kick the tires on that. Do you have an API documentation in any chance (bot for self-hosted and managed), I wasn't able to quickly find it?

Hi, we're working on the API docs, they will be released this week, I'll let you know when it's done

**Comment by yevgenypats** [comment]
> > Hey @Blaumaus , we are starting to kick the tires on that. Do you have an API documentation in any chance (bot for self-hosted and managed), I wasn't able to quickly find it?
> 
> Hi, we're working on the API docs, they will be released this week, I'll let you know when it's done

Sounds great! Will be waiting to hear from you!

**Comment by Blaumaus** [comment]
@yevgenypats we've released some API documentation, it's available here: https://docs.swetrix.com/statistics-api
Let me know if you have some questions related to the documentation or Swetrix code, I'll help you.

**Comment by yevgenypats** [comment]
> @yevgenypats we've released some API documentation, it's available here: https://docs.swetrix.com/statistics-api Let me know if you have some questions related to the documentation or Swetrix code, I'll help you.

Thank you! We will check this out and update!

**Comment by Blaumaus** [comment]
> @Blaumaus Hello :) I am working on the Swetrix plugin right now, and wondering if it would be possible for us to upgrade our account for testing purposes (5 requests per hour is quite restrictive :).
> 
> You can also contact me via email at `shimon@cloudquery.io`.

I've assigned a `freelancer` tier to the account associated with the `shimon@cloudquery.io` email, so there should not be any more issues with the API.

**Comment by shimonp21** [comment]
First version of the plugin is at https://github.com/Swetrix/cq-source-swetrix/pull/1.

**Comment by shimonp21** [comment]
@Blaumaus Thank you! 

Can you please also try to release `v1.0.0`? should be possible by going to https://github.com/Swetrix/cq-source-swetrix/releases and creating a `v1.0.0` tag. You should be able to generate the changelog automatically.

image

Please let me know if you have any trouble creating a release - it probably means that I made some mistake in the relase `.yaml`s.

**Pull request closed without merging**
